### ISSUE TITLE
Spotify fetch code present in file?

### ISSUE THREAD

**Issue by iamxyntho** [staniel359/muffon-api#10]
Hi, I love Muffon and I have seen it develop from the last two years. I am pretty curious about how it works for Spotify, but I can't really find much info on how it works. I can understand code well but I can't seem to find the code that fetches the **Audio Data** from Spotify. If I am not being such a pain, can I kindly get to know where it is?

Thank you so much for building this since it really solves daily life problems that one can think of. You did a good job on this project and it is very well managed but just needs some documentation on how to use the API to **retrieve audio data**.

**Comment by staniel359** [comment]
@iamxyntho Hello.
Thank you very much! I appreciate that.

Sure, no problem.
For audio retrieving I use [this library](https://github.com/kokarare1212/librespot-python).
It's pretty easy to use, but if you need more details I'll provide them to you.

**Comment by iamxyntho** [comment]
Thank you so much for the reply and sorry for this late reply.

I have some questions:
1. Does this library need Spotify premium? 
2. Do you have any plans to develop a mobile application for Muffon? I absolutely can tell everyone wants Muffon on their phone.
3. Do you plan to switch from python to C++/Rust for this API? The API can only handle ~8k requests per second whereas with estimated data, if you use rust, you can handle around ~4.3M requests per second. I guess the API is pretty slow with python for now. These statistics were generated on a server with Intel Xeon 28 cores and 712GB ram
Suggestions: 
1. I think you should add a import playlist from Spotify feature, it would help a lot :)

**Comment by staniel359** [comment]
@iamxyntho
> Does this library need Spotify premium?

No, but the audio quality will be only 160 kbps.
If you have Premium account, you can select better quality.

> Do you have any plans to develop a mobile application for Muffon? I absolutely can tell everyone wants Muffon on their phone.

I've been asked for this multiple times, but:
1. I don't have any experience with mobile development.
2. It will require a huge amount of time.
3. I personally don't like mobile apps experience comparing to desktop ones, mainly because of screen size.
4. It can be completely different technically and some features may not be feasible to implement, e.g. browser tabs.

So it's not planned, sorry.

> Do you plan to switch from python to C++/Rust for this API?

It's not Python, it's Ruby.
And again, it will require a huge amount of time.

> The API can only handle ~8k requests per second whereas with estimated data, if you use rust, you can handle around ~4.3M requests per second. I guess the API is pretty slow with python for now. These statistics were generated on a server with Intel Xeon 28 cores and 712GB ram.

Wow, that's one heck of a machine 😀.
Thanks for the details, very useful.
I think it has something to do with web server (currently [Puma](https://puma.io/)).

> I think you should add a import playlist from Spotify feature, it would help a lot :)

Yes, Spotify intergration is planned.

> Maybe you could provide the documentation on your discord channel?

Sorry, this API wasn't intended to be used by third-party applications in the first place, only by the muffon app itself.
The reason is that it provides full audio links, which can be illegal to be publicly available.

**Comment by iamxyntho** [comment]
Thanks again for the reply!
>tabs I don't have any experience with mobile development.

Can we contribute for the mobile application? 

>tabs It will require a huge amount of time.

So did muffon I guess? You need to start to plan on finishing? 

>tabs It can be completely different technically and some features may not be feasible to implement, e.g. browser tabs.

Browser tabs are pretty much implementable in my experience. I created this application using React native in my office which was basically a web browser for the office staff. I did implement basic tabs very similar to Muffon in the mobile app. It's not the features that you need to be implementable, it's the UI design that needs to properly designed to fit the features.

**Comment by staniel359** [comment]
@iamxyntho I didn't plan to make a mobile version in the first place.
So I'd rather continue developing the app itself.

**Comment by iamxyntho** [comment]
Okay thank you so much! I might now close the issue now.
